name: Generate Songs JSON

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Latest stable version as of now

      - name: Install dependencies
        run: |
          npm install

      - name: Run generateSongsJson
        run: node ./scripts/generateSongsJSON.js

      - name: List files in scripts directory
        run: ls -l scripts/

      - name: List files in main directory
        run: ls -l

      - name: Check for songs.json
        run: |
          if [ -f ./songs/songs.json ]; then
            echo "songs.json exists."
          else
            echo "songs.json does not exist."
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "huntertrapperluke@gmail.com"
          git config --local user.name "lukewdavis"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/lukewdavis/songlibrary.git
          git add songs/songs.json
          git commit -m "Update songs.json" || echo "No changes to commit"
          git push
