name: Generate Songs JSON

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Downgraded to Node.js 14

      - name: Install dependencies
        run: |
          npm install

      - name: Run generateSongsJson
        run: node ./scripts/generateSongsJSON.js  # Ensure the path is correct

      - name: Commit and push changes
        run: |
          git config --local user.email "huntertrapperluke@gmail.com"
          git config --local user.name "lukewdavis"
          git add songs.json
          git commit -m "Update songs.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
